### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Shahensa** [Stipess1/YouPlay#1]
Hello Sir,can you give me database...
Thank You;)

**Comment by Shahensa** [comment]
Sir Please share firebase database..
Thank You;)

**Comment by Stipess1** [comment]
Hm how do you mean share it, app doesn't use firebase database.
I mean there is dependency in gradle but i have to remove it.

**Comment by Shahensa** [comment]
so sir can you explain how we setup firebase for own google json file..
Thank You;)

**Comment by Stipess1** [comment]
Use the `applicationId` value specified in the `app/build.gradle` file of the app as the Android package name, and download the generated `google-services.json` file, and copy it to the `app/` directory
